name: PR Triage by Review Effort
description: A Github Action that uses custom ML model to analyse the effort required to review a given PR in the repository.

branding:
  icon: git-pull-request
  color: green

inputs:
  github-token:
    description: 'Used for GitHub API access'
    required: true
  repo:
    description: 'Repository to analyze'
    required: false
    default: ${{ github.repository }}
  cache-reset:
    description: 'Empty cache before running'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout action
      uses: actions/checkout@v4
      with:
        repository: 'pr-triage-effort/pr-triage-effort-action'
        ref: 'dev'
        path: 'triage-action'

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.14' 
    
    - name: Install Dependencies
      run: pip install -r triage-action/requirements.txt
      shell: bash

    - name: Check for Cached Metrics
      id: cache-metrics
      uses: actions/cache@v3
      with:
        path: ./cache.db
        key: ${{ runner.os }}-pr-analysis-${{ inputs.repo }}-${{ github.ref }}
        restore-keys: |
            ${{ runner.os }}-pr-analysis-${{ inputs.repo }}-

    - name: Run Analysis
      run: python triage-action/src/v2_sql/analysis.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPO:  ${{ inputs.repo }}
        RESET_CACHE:  ${{ inputs.cache-reset }}
        PYTHONUNBUFFERED: 1
      
    - name: Upload ranking JSON as artifact
      uses: actions/upload-artifact@v4
      with:
        name: analysis-results
        path: ./results.json
