name: 'PR Triage by Review Effort'
description: 'A Github Action that uses custom ML model to analyse the efffort required to review a given PR inthe repository.
branding:
  icon: 'git-pull-request'
  color: 'green'

inputs:
  github-token:
    description: 'Used for GitHub API access'
    required: true
  repo:
    description: 'Repository to analyse'
    required: true
  cache-reset:
    description: 'Empty cache before running'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.14' 
    
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Check for Cached Metrics
      id: cache-metrics
      uses: actions/cache@v3
      with:
        path: ./cache.json
        key: ${{ runner.os }}-pr-analysis-${{ github.repository }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
            ${{ runner.os }}-pr-analysis-${{ github.repository }}-${{ github.ref }}-

    - name: Run Analysis
      run: python src/analysis.py -u
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPO:  ${{ inputs.repo }}
        CACHE_RESET:  ${{ inputs.cache-reset }}
        PYTHONUNBUFFERED: 1
      
    - name: Upload ranking JSON as artifact
      uses: actions/upload-artifact@v4
      with:
        name: analysis-results
        path: ./results.json
