name: Test Action

on: 
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo to analyse'
        required: true
      db:
        description: 'Path to existing db file'
        required: false

jobs:
  test-on-public:
    runs-on: ubuntu-latest
    name: Runs analysis on specified repo
    timeout-minutes: 1440
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: test action
        uses: ./ # Uses an action in the root directory
        with:
          github_token: ${{ secrets.TEST_API_TOKEN_FRc }}
          repo: ${{ inputs.repo }}
          use_model: 'false'
          db_path: ${{ inputs.db }}
