name: Test Action
description: Workflow to manually test the GitHub action on any public repo

on: 
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo to analyse'
        required: true

jobs:
  test-on-public:
    runs-on: ubuntu-latest
    name: Runs analysis on specified repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test action
        uses: ./ # Uses an action in the root directory
        with:
          github-token: ${{ secrets.TEST_API_KEY }}
          repo: ${{ inputs.repo }}
